### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by iProgYou** [mmbarness/recordcollector#1]
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments

**Comment by iProgYou** [comment]
Try to format it similar to how bluebird is.

I think the label MVP may be a bit much. We should chat about this one

**Comment by iProgYou** [comment]
Still gotta format

**Comment by iProgYou** [comment]
May want to do artist page and album page before labels
